/*
 * This file is generated by jOOQ.
 */
package com.example.db;


import com.example.db.tables.Author;
import com.example.db.tables.Book;
import com.example.db.tables.BookStore;
import com.example.db.tables.BookToBookStore;
import com.example.db.tables.Language;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DefaultSchema extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>DEFAULT_SCHEMA</code>
     */
    public static final DefaultSchema DEFAULT_SCHEMA = new DefaultSchema();

    /**
     * The table <code>AUTHOR</code>.
     */
    public final Author AUTHOR = Author.AUTHOR;

    /**
     * The table <code>BOOK</code>.
     */
    public final Book BOOK = Book.BOOK;

    /**
     * The table <code>BOOK_STORE</code>.
     */
    public final BookStore BOOK_STORE = BookStore.BOOK_STORE;

    /**
     * The table <code>BOOK_TO_BOOK_STORE</code>.
     */
    public final BookToBookStore BOOK_TO_BOOK_STORE = BookToBookStore.BOOK_TO_BOOK_STORE;

    /**
     * The table <code>LANGUAGE</code>.
     */
    public final Language LANGUAGE = Language.LANGUAGE;

    /**
     * No further instances allowed
     */
    private DefaultSchema() {
        super("", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            Author.AUTHOR,
            Book.BOOK,
            BookStore.BOOK_STORE,
            BookToBookStore.BOOK_TO_BOOK_STORE,
            Language.LANGUAGE);
    }
}
