/*
 * This file is generated by jOOQ.
 */
package com.example.db;


import com.example.db.tables.Author;
import com.example.db.tables.Book;
import com.example.db.tables.BookStore;
import com.example.db.tables.BookToBookStore;
import com.example.db.tables.Language;


/**
 * Convenience access to all tables in the default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>AUTHOR</code>.
     */
    public static final Author AUTHOR = Author.AUTHOR;

    /**
     * The table <code>BOOK</code>.
     */
    public static final Book BOOK = Book.BOOK;

    /**
     * The table <code>BOOK_STORE</code>.
     */
    public static final BookStore BOOK_STORE = BookStore.BOOK_STORE;

    /**
     * The table <code>BOOK_TO_BOOK_STORE</code>.
     */
    public static final BookToBookStore BOOK_TO_BOOK_STORE = BookToBookStore.BOOK_TO_BOOK_STORE;

    /**
     * The table <code>LANGUAGE</code>.
     */
    public static final Language LANGUAGE = Language.LANGUAGE;
}
